name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [ final, work-in-progress ]
    paths-ignore:
      - .github/workflows/**
      - docs/**
      - LICENSE
      - README.md
  pull_request:
    branches: [ final, work-in-progress ]
    paths-ignore:
      - .github/workflows/**
      - docs/**
      - LICENSE
      - README.md

jobs:
  ubuntu_22_04:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc-12, cxx: g++-12 }
          - { cc: gcc-11, cxx: g++-11 }
          - { cc: gcc-10, cxx: g++-10 }
    name: Ubuntu 22.04 ${{ matrix.compiler.cc }}
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update -q
          sudo apt-get install -y ${{ matrix.compiler.cc }} ${{ matrix.compiler.cxx }} build-essential dkms git iw
      - name: Build
        run: |
          make clean
          make -j"$(nproc)" CC=${{ matrix.compiler.cc }} CXX=${{ matrix.compiler.cxx }}

  ubuntu_20_04:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc-11, cxx: g++-11 }
          - { cc: gcc-10, cxx: g++-10 }
          - { cc: gcc-9,  cxx: g++-9  }
    name: Ubuntu 20.04 ${{ matrix.compiler.cc }}
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update -q
          sudo apt-get install -y ${{ matrix.compiler.cc }} ${{ matrix.compiler.cxx }} build-essential dkms git iw
      - name: Build
        run: |
          make clean
          make -j"$(nproc)" CC=${{ matrix.compiler.cc }} CXX=${{ matrix.compiler.cxx }}