name: Build CI

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ final, work-in-progress ]
    paths-ignore:
      - .github/workflows/**
      - docs/**
      - LICENSE
      - README.md
  pull_request:
    branches: [ final, work-in-progress ]
    paths-ignore:
      - .github/workflows/**
      - docs/**
      - LICENSE
      - README.md

jobs:
  ubuntu_24_04:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc-14 }
          - { cc: gcc-13 }
          - { cc: gcc-12 }
    name: Ubuntu 24.04 ${{ matrix.compiler.cc }}
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update -q
          sudo apt-get install -y ${{ matrix.compiler.cc }} build-essential dkms git iw
      - name: Build
        run: |
          make clean
          make -j"$(nproc)" CC=${{ matrix.compiler.cc }}

  ubuntu_22_04:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc-12 }
          - { cc: gcc-11 }
          - { cc: gcc-10 }
    name: Ubuntu 22.04 ${{ matrix.compiler.cc }}
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update -q
          sudo apt-get install -y ${{ matrix.compiler.cc }} build-essential dkms git iw
      - name: Build
        run: |
          make clean
          make -j"$(nproc)" CC=${{ matrix.compiler.cc }}
