name: Codespell CI
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ final, work-in-progress ]
  pull_request:
    branches: [ final, work-in-progress ]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update -y && sudo apt-get install -y codespell
      - name: Run codespell
        run: |
          find . -type f \( -name '*.sh' -o -name '*.md' \) -print0 | xargs -0 -n1 codespell