name: Markdown link CI
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ final, work-in-progress ]
    paths: [ '**.md' ]
  pull_request:
    branches: [ final, work-in-progress ]
    paths: [ '**.md' ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1